defaults: &defaults
  docker:
  - image: rajashrik/de-infrabox-v1
  working_directory: /home/circleci/project

version: 2
jobs:
 dummy:
    <<: *defaults
    steps:
    - run:
        command: echo "hello world"

 build:
    <<: *defaults
    steps:
    - checkout
    - run:
        command: source /okta_venv/bin/activate;
                ./scripts/create_tf_state_bucket.sh $TRAINING_COHORT;
                ./scripts/create_key_pair.sh $TRAINING_COHORT;
#                ./scripts/build_ami.sh training_kafka
#                ./scripts/build_ami.sh training_ingester
    - run:
        command: source /okta_venv/bin/activate;
                ./scripts/run_terraform.sh $TRAINING_COHORT base_networking apply -input=false -auto-approve;
                ./scripts/run_terraform.sh $TRAINING_COHORT bastion apply -input=false -auto-approve;
                ./scripts/run_terraform.sh $TRAINING_COHORT training_bucket apply -input=false -auto-approve;
                ./scripts/run_terraform.sh $TRAINING_COHORT training_emr_cluster apply -input=false -auto-approve;
                ./scripts/run_terraform.sh $TRAINING_COHORT training_kafka apply -input=false -auto-approve;
                ./scripts/run_terraform.sh $TRAINING_COHORT ingester apply -input=false -auto-approve;
                ./scripts/run_terraform.sh $TRAINING_COHORT monitoring_dashboard apply -input=false -auto-approve;

 destroy:
    <<: *defaults
    steps:
    - checkout
    - run:
        command: source /okta_venv/bin/activate;
                ./scripts/run_terraform.sh $TRAINING_COHORT base_networking destroy -input=false -auto-approve;
                ./scripts/run_terraform.sh $TRAINING_COHORT bastion destroy -input=false -auto-approve;
                ./scripts/run_terraform.sh $TRAINING_COHORT training_bucket destroy -input=false -auto-approve;
                ./scripts/run_terraform.sh $TRAINING_COHORT training_emr_cluster destroy -input=false -auto-approve;
                ./scripts/run_terraform.sh $TRAINING_COHORT training_kafka destroy -input=false -auto-approve;
                ./scripts/run_terraform.sh $TRAINING_COHORT ingester destroy -input=false -auto-approve;
                ./scripts/run_terraform.sh $TRAINING_COHORT monitoring_dashboard destroy -input=false -auto-approve;

workflows:
  version: 2
  build:
    jobs:
      - dummy
      - build:
          type: approval
          requires:
            - dummy
      - destroy:
          type: approval
          requires:
            - dummy
